blog/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'Accounts'


urlpatterns =[
    path('signup/', views.signup_view, name = 'SignUP'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

blog/app/urls.py
from django.contrib import admin
from django.urls import path
from . import views




app_name = 'Articles'


urlpatterns = [
    path("", views.home, name='home'),
    path('articles/<slug>', views.article_details, name = 'articles'),
    path('index/', views.index, name ='index'),
    path('create/', views.create, name='create'),
    path('members/<name>', views.members, name='members'),
    path('drivers/', views.drivers, name='drivers')
    



    # path("results/<int:question_id>/", views.results, name="results"),
    # path('testing/<int:numbering>', views.testing, name = 'testing'),
]

    

blog/blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('app.urls')),
    path("accounts/", include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/accounts/models.py
from django.db import models

# Create your models here.
 

blog/app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)




    def __str__(self):
        return self.title 
    



class Student(models.Model):
    name = models.TextField()
    VeryPoor = 'Very Poor'
    Poor = 'Poor'
    Mid = 'Normal'
    Rich = 'Rich'
    VeryRich = 'Very Rich'
    CHOICES = [
        (Poor, "Poor"),
        (VeryPoor, "Very Poor"),
        (Mid, "Mid"),
        (Rich, " Rich"),
        (VeryRich, "Very Rich")]
    
    Finances = models.CharField(
        max_length=9,
        choices=CHOICES,
        default='mid',
    )
    
    body = models.TextField()
    
    def __str__(self):
        return self.name
    
    def shorten(self):
        return self.body[:50] + '...'
    


class Drivers(models.Model):
    TEAMS = (
    ('RedBull' , 'Redbull'),
    ('Mercedes' , 'Mercedes'),
    ('AstonMartin' , 'Aston Martin'),
    ('Ferrari', 'Ferrari'),
    ('AlphaTauri', 'Alpha Tauri'),
    ('AlphaRomeo', 'Alpha Romeo'),
    ('Williams', 'Williams'),
    ('Hass', 'Hass'),
    ('McLaren', 'McLaren'),
    ('Alpine', 'Alpine'),
    )
    
    name = models.TextField()
    team = models.CharField(max_length=20, choices=TEAMS)
    thumb = models.ImageField(default='default_f1.jpeg', blank=True)


    def __str__(self):
        return self.name

blog/app/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model=models.Article
        fields = ['title', 'body', 'slug', 'thumb']

blog/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            login(request, user)
        
            return redirect('Articles:home')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})

def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('Articles:home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method =='POST':
        logout(request)
        return render(request, 'logout.html')
    
     

blog/app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Article, Student, Drivers
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.


def article_details(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles.html', {'articles': article})
    

   
def home(request):
    articles = Article.objects.all()
    names = Student.objects.all()
    return render(request, 'home.html',   {'names':names,'articles': articles , 'username':request.user.username})

def index(request):
    return render(request, 'index.html')


def members(request, name):
    Members = Student.objects.get(name=name, )
    
    
    return render(request, 'members.html', {'members': Members})


def drivers(request):
        Drivers_list = Drivers.objects.all()
        return render(request, 'Drivers.html', {'Drivers':Drivers_list})


@login_required(login_url='Accounts:login')
def create(request):
     
     if request.method=='POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid:
            instance =  form.save(commit=False)
            instance.author = request.user
            instance.save()
            
            return redirect('Articles:home')
        
        else:
            form=forms.CreateArticle()
            
     else:
        form = forms.CreateArticle()
        return render(request, 'create.html', {'form': form})









#def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

#def article_list(request):
#     articles = Article.objects.all().order_by('date')
#     return render(request, 'articles_list.html', {'article':articles})

blog/accounts/templates/accounts/login.html
{% extends 'base.html'%}

{% block content%}
<h1>Log-in Page</h1>

<form class="site-form" action="{%url 'Accounts:login'%}" method="post"> 
    {%csrf_token%}
    {{form}}
    {%if request.GET.next%} 
       <input type ='hidden' name="next" value="{{request.GET.next}}"> 
    
    {%endif%}
    <input type="submit" value="Login">
</form>
{%endblock%}

blog/accounts/templates/accounts/signup.html
{% extends 'base.html'%}

{% block content%}
<h1>Sign-up Page</h1>

<form class="site-form" action="/accounts/signup/" method="post"> 
    {%csrf_token%}
    {{form}}
    <input type="submit" value="sign-up">
</form>
{%endblock%}

blog/templates/Drivers.html
{%extends 'base.html'%}

{% block content%}


<h1>Drivers template</h1>

{%for driver in Drivers%} 
<h1>{{driver.name}}</h1>
<p>{{driver.team}}</p>
<img src = {{driver.thumb.url}} width="100pt" height="100pt" />
{%endfor%}


{% endblock %}

blog/templates/articles.html
{%extends 'base.html'%}


{% block content%}



<img src = {{articles.thumb.url}} width = 40% height =40% />

<h1>{{articles.title}}</h1>

<p>{{articles.body}}</p>

<p>{{articles.date}}</p>





{%endblock%}

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
           
        <link rel="stylesheet"  href= "{% static 'styles.css'%}">
    </head>
    <body>
        <header class = 'wrapper'>
            <a href="{%url 'Articles:home'%}"> <img src = "{% static 'Images/Firefly.png'%}"  width="50%", height="50%"/> </a>

            <nav>
                <ul>    
                    {% if user.is_authenticated%}
                    <li>
                        <form class = 'log-out link' action = "{%url 'Accounts:logout'%}" method = 'POST'> 
                        {%csrf_token%}
                        <button type="submit"> Logout </button>
                        </form>
                    </li>
                    
                    <li><form class="Create link" action="{%url 'Articles:create'%}" method = 'POST'>
                        {%csrf_token%}
                    <button type="submit">Create</button>
                    </form>
                    </li>
    

                        
                    
                    {% else%}
                    <li>
                        <form class = 'log-in link' action = "{%url 'Accounts:login'%}" method = 'POST'> 
                        {%csrf_token%}
                        <button type="submit"> Login </button>
                        </form>

                        

                        
                    </li>


                    {%endif%}
                </ul>
            </nav>
        </header>
        <div class ='wrapper'>

            {% block content%}
            {% endblock%}
        </div>
    </body>


</html>

blog/templates/create.html
{%extends 'base.html'%}


{%block content%} 
<div class = 'create-article'> 
    <h2>Create a new Article</h2>
    <form class="site-form" method="post" action="{%url 'Articles:create'%}">
        {%csrf_token%}
        {{form}}
        <input type="submit" value="create">
    </form>
</div>
{%endblock%} 
 

blog/templates/home.html
{%extends 'base.html'%}


{% block content%}




<!-- <img src = '/static/Images/Firefly.png'/> -->
<head><title>HOME</title></head>
<home>The Home Page</home>

<h1> Currently loggin in as: {{username}}</h1>









{%  comment %}
<div class="names">
    {% for name in names %}
        <div class = 'names \n'>   
        <h3><a href="{%url 'Articles:members' name.name%}">The Name: {{name.name}}</a> </h3>
        <p>Their Financial status: {{name.Finances}}</p>
        </div>
        <p>The body of the Student: {{name.shorten}}</p>
    {% endfor %}
</div>

{%endcomment%}


<h1>The Articles present are:</h1>
<div class = 'articles'>

    {%for article in articles%}

        <div class = 'articles \n'>
            <p> <a href="{%url 'Articles:articles' article.slug%}">{{article.title}}</a></p>
            <n>Date: {{article.date}}</n>
            <a href="{%url 'Articles:articles' article.slug%}"> <img src = {{article.thumb}} width = 40% height =40% /> </a>
        </div>
    {%endfor%}


</div>



 {%endblock%}

blog/templates/index.html
{%extends 'base.html'%}


{% block content%}

<h1>This page shall be used to test proposed webpages.</h1>

{%endblock%}

blog/templates/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    
    <nav>
        <ul>    
            <li>
                <form class = 'log-in link' action = "{%url 'Accounts:login'%}" method = 'POST'> 
                {%csrf_token%}
                <button type="submit"> Login </button>
                </form>
            </li>
        </ul>
    </nav>
{% endblock  %}

blog/templates/members.html
{%extends 'base.html'%}


{% block content%}





<h1>{{members.name}}</h1>

<p>{{members.Finances}}</p>

<p>{{members.body}}</p>



{%endblock%}